FROM golang:1.26.1-alpine@sha256:2389ebfa5b7f43eeafbd6be0c3700cc46690ef842ad962f6c5bd6be49ed82039 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-w -s" -o /control-plane ./cmd/control-plane
FROM alpine:3.22@sha256:5291449c3df73caf6ed85e649dec1b9e818b39a5d8c871e97afc13e9cd5e8fa8
RUN apk --no-cache add ca-certificates curl && mkdir /audit && chown 65532:65532 /audit
COPY --from=builder /control-plane /app/control-plane
USER 65532:65532
EXPOSE 8080
ENTRYPOINT ["/app/control-plane"]
