FROM golang:1.27.1-alpine@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-w -s" -o /control-plane ./cmd/control-plane
FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
RUN apk --no-cache add ca-certificates curl && mkdir /audit && chown 65532:65532 /audit
COPY --from=builder /control-plane /app/control-plane
USER 65532:65532
EXPOSE 8080
ENTRYPOINT ["/app/control-plane"]
